#SPDX-License-Identifier: MIT-0
---
- name: Create Droplet
  digitalocean.cloud.droplet:
    token: "{{ token }}"
    state: present
    name: example.com
    region: nyc3
    size: s-1vcpu-1gb
    image: ubuntu-22-04-x64
