---
- hosts: all
  become: true
  tasks:
    - name: upgrade the packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
    - name: Copy file from local to remote
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: "0644"
